---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - shipyard.sthings.tiab.ssc.sva.de
  resources:
  - shipyardterraforms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shipyard.sthings.tiab.ssc.sva.de
  resources:
  - shipyardterraforms/finalizers
  verbs:
  - update
- apiGroups:
  - shipyard.sthings.tiab.ssc.sva.de
  resources:
  - shipyardterraforms/status
  verbs:
  - get
  - patch
  - update
