apiVersion: shipyard.sthings.tiab.ssc.sva.de/v1beta1
kind: ShipyardTerraform
metadata:
  labels:
    app.kubernetes.io/name: shipyardterraform
    app.kubernetes.io/instance: shipyardterraform-sample
    app.kubernetes.io/part-of: shipyard-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: shipyard-operator
  name: shipyardterraform-sample
spec:
  terraform-version: 1.4.4
  template: vsphere-vm
