---
apiVersion: v1
metadata:
  name: sthings-vault
  namespace: shipyard-operator-system
  labels:
    app.kubernetes.io/part-of: shipyard-operator
stringData:
  VAULT_TOKEN: ${VAULT_TOKEN}
  VAULT_NAMESPACE: ${VAULT_NAMESPACE}
  VAULT_ADDR: ${VAULT_ADDR}
kind: Secret
type: Opaque