apiVersion: v2
name: shipyard-operator
description: A Helm chart for Kubernetes
type: application
version: v0.1.128
appVersion: v0.1.128
dependencies:
  - name: sthings-helm-toolkit
    version: v0.1.125
    repository: oci://eu.gcr.io/stuttgart-things
    #repository: file://../../../sthings-helm-toolkit
